sudo: required
services:
    - docker

before_install:
    - docker build -t birindocker/frontend-react -f Dockerfile.dev .

script:
    - docker run -e CI=true birindocker/frontend-react npm run test

before_deploy: "echo env;"

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-us-east-2-334705876806"
    on:
        branch: master
    access_key_id:
        secure: "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"