sudo: required
services:
    - docker

before_install:
    - docker build -t birindocker/frontend-react -f Dockerfile.dev .

script:
    -  docker run birindocker/frontend-react npm run test -- --coverage